In [61]:
import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data,index=labels)
print("1)")
print(df.head(3))
print("2)")
print(df.dropna())
print("3)")
print(df.iloc[[1, 3, 5, 6], [0, 1]])
print("4)")
df.loc['k'] = [1, 'Suresh', 'yes', 15.5]
print(df)
print("5)")
df.pop('attempts')
print(df)
print("6)")

Success = [1,0,1,0,0,0,1,1,0,0,1]
df["Success"]=Success
print(df)

1)
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
2)
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
3)
      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5
4)
        name   score attempts qualify
a  Anastasia    12.5        1     yes
b       Dima       9        3      no
c  Katherine    16.5        2     yes
d      James     NaN        3      no
e      Emily       9        2      no
f    Michael      20        3     yes
g    Matthew    14.5        1     yes
h      Laura     NaN        1      no
i      Kevin       8        2      no
j      Jonas      19        1     yes
k          1  Suresh      yes    15.5
5)
        name   score qualify
a  Anastasia    12.5     yes
b       Dima       9      no
c  Katherine    16.5     yes
d      James     NaN      no
e      Emily       9      no
f    Michael      20     yes
g    Matthew    14.5     yes
h      Laura     NaN      no
i      Kevin       8      no
j      Jonas      19     yes
k          1  Suresh    15.5
6)
        name   score qualify  Success
a  Anastasia    12.5     yes        1
b       Dima       9      no        0
c  Katherine    16.5     yes        1
d      James     NaN      no        0
e      Emily       9      no        0
f    Michael      20     yes        0
g    Matthew    14.5     yes        1
h      Laura     NaN      no        1
i      Kevin       8      no        0
j      Jonas      19     yes        0
k          1  Suresh    15.5        1